# Generated by Django 4.1.6 on 2023-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
