# Generated by Django 4.1.6 on 2023-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_done',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
