# Generated by Django 4.1.6 on 2023-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_goal_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
