# Generated by Django 4.1.6 on 2023-04-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='goal_mode',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
