# Generated by Django 4.1.5 on 2023-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_posts_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='popu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
