# Generated by Django 4.1.6 on 2023-02-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_studysummary_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysummary',
            name='topic',
        ),
        migrations.AddField(
            model_name='studysummary',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
