# Generated by Django 4.1.6 on 2023-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
