# Generated by Django 4.1.6 on 2023-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_videowatchprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatchprogress',
            name='progress',
            field=models.DurationField(),
        ),
    ]
