# Generated by Django 4.1.6 on 2023-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.CharField(default='00:02:13', max_length=100),
        ),
    ]
