# Generated by Django 4.1.6 on 2023-06-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_video_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tutorial',
            new_name='courses',
        ),
    ]
