# Generated by Django 4.1.6 on 2023-06-19 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatchprogress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videowatchprogress',
            name='progress',
            field=models.CharField(max_length=20),
        ),
    ]
