# Generated by Django 4.1.6 on 2023-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_videowatchprogress_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatchprogress',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
